name: Build Release

# automated build dist and tarball
# repo    : https://github.com/dimaslanjaka/nodejs-package-types/blob/main/.github/workflows/build-release.yml
# raw     : https://raw.githubusercontent.com/dimaslanjaka/nodejs-package-types/main/.github/workflows/build-release.yml
# update  : curl -L https://github.com/dimaslanjaka/nodejs-package-types/raw/main/.github/workflows/build-release.yml > .github/workflows/build-release.yml

on:
  push:
    branches: ['master', 'main', 'private']
    paths-ignore:
      - '**/*.tgz'
      - '**/*.gz'
      - '**/release/**'
      - '**garbage-collector**'
      - '**codeql**'
      - '**/.github/workflows/tester.yml'
  pull_request:
    types:
      - closed
    paths-ignore:
      - '**/release/**'
      - '**/*.tgz'
      - '**/*.gz'
      - '**/test*/**'
  workflow_dispatch:

# run single job
concurrency:
  group: build-release
  cancel-in-progress: true

jobs:
  build-release:
    name: build release
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      node-version: 20.x
      YARN_CHECKSUM_BEHAVIOR: update

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set EOL git configs
        continue-on-error: true
        run: |
          git config core.eol lf
          git config core.autocrlf input
          git checkout-index --force --all

      - name: Pull & update submodules recursively
        continue-on-error: true
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          git pull -X theirs
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install

      - name: initialize nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
            ./.yarn/cache*
            ./.yarn/*.gz
            **/dist
            **/.yarn/cache*
            **/node_modules
            **/tmp
            **/*.lock
            **/db.json
          key: ${{ runner.os }}-${{ hashFiles('src/**/*.js', 'src/**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          corepack enable
          touch yarn.lock
          yarn install

      - name: Run deploy
        run: yarn run deploy
